spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://j9b306.p.ssafy.io:3306/B306?serverTimezone=Asia/Seoul
    username: developer
    password: fjksdg

django:
  server:
    url: "http://j9b306.p.ssafy.io:8000"  # Django 서버